[package]
name = "museical"
version = "0.1.0"
authors = ["Tom Burdick <tom.burdick@electromatic.us>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
heapless = "0.5"
